### ISSUE TITLE
Flask db upgrade -head needed

### ISSUE THREAD

**Issue by SWhalley1130** [learn-co-curriculum/python-p4-authorization-lab#3]
### Canvas Link

https://learning.flatironschool.com/courses/6267/assignments/236240?module_item_id=554264

### Concern

Cannot run `flask db upgrade` as requested in the instructions due to mutliple heads. Instructions should be updated to reflect most recent head, or versions 'a76dbcefe654' and '2c6454d9acb2' should be deleted out of the versions folder.

![image](https://user-images.githubusercontent.com/98498031/231587760-f36176a6-465c-46b9-949c-2ee7de3a37b8.png)

**Comment by professor-ben** [comment]
Starting on this now- thanks for the report!
